### ISSUE TITLE
Serialization issue with elasticsearch and mongo connector

### ISSUE THREAD

**Issue by SVPD-HenryKwan** [yougov/mongo-connector#152]
When I try to use the mongo-connector to send a field that is a UUID that isn't the _id field it throws a serialization error:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/oplog_manager.py", line 439, in dump_collection
    dm.bulk_upsert(docs_to_dump())
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 41, in wrap
    return func(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 122, in bulk_upsert
    chunk_size=self.chunk_size)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/**init**.py", line 145, in bulk
    for ok, item in streaming_bulk(client, actions, *_kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/**init**.py", line 104, in streaming_bulk
    resp = client.bulk(bulk_actions, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(_args, params=params, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 646, in bulk
    params=params, body=self._bulk_body(body))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 135, in _bulk_body
    body = '\n'.join(map(self.transport.serializer.dumps, body))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/serializer.py", line 47, in dumps
    raise SerializationError(data, e)
SerializationError: ({u'ProjectId': UUID('45251a04-7e63-be43-a848-a2377ba87f12'), u'_id': '0003bcd2-240c-1f44-8d0f-a0acae5714b3', 'ns': 'files.filemain', '_ts': 6040053173115158529}, TypeError())

**Comment by Bhashit** [comment]
I know this issue is closed, but I had a related question. The connector uses `uuid.hex` to convert mongo UUIDs to string, to be stored in Elasticsearch. My code is in scala, and the standard API expects a UUID in the hyphenated string format that is returned by `str(uuid)` in python. Since converting these to my expected format in the scala code isn't very palatable for a few reasons, I was thinking of forking the repo and overriding just that part. That is, use `str(uuid)` instead of `uuid.hex`. Would that be a bad idea?
