### ISSUE TITLE
MongoConnector fails upon update with $unset parameter

### ISSUE THREAD

**Issue by mimkorn** [yougov/mongo-connector#160]
While working on #159 ticket I thought there was an error with my edit python doc_manager script. However, I tried it with a completely new fresh install of mongo-connector with the original doc_manager and the failure happens anyway, so this is a new issue.

To repeat the failure:
1. I start the mongo-connector like this:
mongo-connector -m 127.0.0.1:27017 -t http://localhost:8983/solr -d C:\Python27\Lib\site-packages\mongo_connector\doc_managers\solr_doc_manager.py -n myDB.myCOLL
2. I run in the mongo shell this update: db.myCOLL.update({},{$unset:{someField:""}},{multi:true}). 

MongoConnector runs correctly until it is supposed to work with this last command. It throws an exception like:

```
Exception in thread Thread-2:
Traceback (most recent call last):
 File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
 File "C:\Python27\lib\site-packages\mongo_connector\oplog_manager.py", line 233, in run
    docman.update(doc, entry.get('o', {}))
 File "C:\Python27\lib\site-packages\mongo_connector\doc_managers\__init__.py", line 24, in wrapped
     return f(*args, **kwargs)
  File "C:\Python27\Lib\site-packages\mongo_connector\doc_managers\solr_doc_manager.py", line 187,    in update
    updated = self.apply_update(doc, update_spec)
  File "C:\Python27\Lib\site-packages\mongo_connector\doc_managers\solr_doc_manager.py", line 170, in apply_update
    doc.pop(to_unset)
KeyError: u'someField'
```

I tried it on 1.2.1. It is working on the older version, so it must be a new introduced bug.

**Comment by mimkorn** [comment]
Hope commenting won't reopen it! I just wanted to say a very late thanks. The project moved it's focus for a long while to a different development issues and I finally found time to try it out and it seems to work just fine. Thank you very much for your efforts!
