### ISSUE TITLE
not authorized for query on config.shards

### ISSUE THREAD

**Issue by dongtong** [yougov/mongo-connector#182]
Hi,

When I use shard cluster, and use 
mongo-connector -m localhost:20000 -t http://localhost:8080/solr/core0 --auto-commit-interval=0 -d solr_doc_manager.py command, the terminal report:

pymongo.errors.OperationFailure: database error: not authorized for query on config.shards

BTW, I use authentication for admin database, so  how to use mongo-connector command?

Thanks

**Comment by Morriaty-The-Murderer** [comment]
Hello, @llvtt
I got problems with authentication.
I can access mongo directly
```bash
mongo <host>:<port>/dbname -u <user> -p
``` 
But when using mongo-connector, it raised auth failure.
I've tried two of this
```bash
mongo-connector -m mongodb://<user>:<password>@<host>:<port> -t localhost:9200 -d elastic2_doc_manager -n db.collection
mongo-connector -m <host>:<port> -t localhost:9200 -d elastic2_doc_manager -n db.collection -a <user> -p <password>
```

This is the error msg
```bash
Logging to mongo-connector.log.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mongo_connector/connector.py", line 262, in run
    main_conn['admin'].authenticate(self.auth_username, self.auth_key)
  File "/usr/local/lib/python2.7/site-packages/pymongo/database.py", line 1023, in authenticate
    connect=True)
  File "/usr/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 424, in _cache_credentials
    sock_info.authenticate(credentials)
  File "/usr/local/lib/python2.7/site-packages/pymongo/pool.py", line 317, in authenticate
    auth.authenticate(credentials, self)
  File "/usr/local/lib/python2.7/site-packages/pymongo/auth.py", line 436, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/local/lib/python2.7/site-packages/pymongo/auth.py", line 418, in _authenticate_default
    return _authenticate_mongo_cr(credentials, sock_info)
  File "/usr/local/lib/python2.7/site-packages/pymongo/auth.py", line 411, in _authenticate_mongo_cr
    sock_info.command(source, query)
  File "/usr/local/lib/python2.7/site-packages/pymongo/pool.py", line 213, in command
    read_concern)
  File "/usr/local/lib/python2.7/site-packages/pymongo/network.py", line 99, in command
    helpers._check_command_response(response_doc, None, allowable_errors)
  File "/usr/local/lib/python2.7/site-packages/pymongo/helpers.py", line 196, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: auth fails
```

**Comment by Morriaty-The-Murderer** [comment]
Hi, @llvtt 
I‘ve looked into the source code, found that it was because the authentication was done on db `admin`
```python
main_conn['admin'].authenticate(self.auth_username, self.auth_key)
```

So where did the cli arg `-n NS_SET, --namespace-set=NS_SET` effect?
I suppose it should be 
```
main_conn[NS_SET].authenticate(self.auth_username, self.auth_key)
```
but can't find any relevant line in the source code

**Comment by llvtt** [comment]
Hi @Morriaty-The-Murderer ,

The user has to be in the admin database because the privileges the user needs are only available in that database. Please see the following: https://github.com/mongodb-labs/mongo-connector/wiki/Usage-with-Authentication#required-permissions.
