### ISSUE TITLE
not all fields are copied from mongodb to solr after integration using mongo-connector

### ISSUE THREAD

**Issue by sridharrao** [yougov/mongo-connector#74]
I am able to successfully integrate between MONGODB & SOLR, using MONGO-CONNECTOR. And whenever, I update or add any thing, in the sample collection i have created, it copies only two or three fields in a documents, and rest of the fields data are not copied into solr. This is some thing I am not able to do it.

This is my collection and its document details. Name of collection: testdb

document inserted as follows:

db.testdb.insert( {
...  _id: "101",
...  name: "test",
...  description: "descr",
...  mydesc: "mydescr",
...  nmdsc: "nmdsc1",
...  coords: "coords1"
...  })

And the data sync between solr and mongo logs says successful:
2014-01-17 19:35:38,462 - INFO - Finished 'http://<hostname>:<port>/solr/update/?commit=true' (post) with body '<add><doc>' in 0.210 seconds.

But when I execute a query to see the document data it says only these fields data:

{
    "responseHeader": {
        "status": 0,
        "QTime": 0,
        "params": {
            "q": "_:_",
            "wt": "json"
        }
    },
    "response": {
        "numFound": 1,
        "start": 0,
        "docs": [
            {
                "id": "101",
                "description": "descr",
                "name": "test",
                "_version_": 1457486601392226300
            }
        ]
    }
}

Clearly i can see that following fields & respective data are not copied into solr:

...  mydesc: "mydescr",
...  nmdsc: "nmdsc1",
...  coords: "coords1"

Following is my schema.xml:

For some reason the schema.xml is not getting copied, it can be found in the following link, which I had raised question in stackoverflow a week ago:

http://stackoverflow.com/questions/21188334/not-all-fields-are-copied-from-mongodb-to-solr-after-integration-using-mongo-con

**Comment by coolraaj15** [comment]
Hi Luke & Sridhar,

I am new here for mongo connector with solr+mongo.
Can you please help me here 
I am running command after setting up my replica set of mongo
C:\Python27\Scripts>mongo-connector -m ppispcw28:27017 -n admin.servicenow -t http://estpcsw173:8983/solr/#/ -d solr_doc_manager

Output:
No handlers could be found for logger "mongo_connector.util"
Traceback (most recent call last):
  File "C:\Python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\mongo-connector.exe\__main__.py", line 9, in <module>
  File "C:\Python27\lib\site-packages\mongo_connector\util.py", line 85, in wrapped
    func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\mongo_connector\connector.py", line 998, in main
    conf.parse_args()
  File "C:\Python27\lib\site-packages\mongo_connector\config.py", line 114, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names))
  File "C:\Python27\lib\site-packages\mongo_connector\connector.py", line 789, in apply_doc_managers
    dm_instances.append(module.DocManager(target_url, **kwargs))
  File "C:\Python27\lib\site-packages\mongo_connector\doc_managers\solr_doc_manager.py", line 76, in __init__
    self._build_fields()
  File "C:\Python27\lib\site-packages\mongo_connector\util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\mongo_connector\doc_managers\solr_doc_manager.py", line 95, in _build_fields
    result = decoder.decode(declared_fields)
  File "C:\Python27\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Please help me here

**Comment by llvtt** [comment]
@coolraaj15 This issue has been closed. If you're asking a new question, please create another issue.

**Comment by coolraaj15** [comment]
Sure
