### ISSUE TITLE
solr mongo-connector Index a 10m document, solr error:OutOfMemoryError Java heap space

### ISSUE THREAD

**Issue by nyf1993** [yougov/mongo-connector#779]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\mongo_connector\util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "d:\python\lib\site-packages\mongo_connector\doc_managers\solr_doc_manager.py", line 271, in upsert
    commitWithin=u(self.auto_commit_interval))
  File "d:\python\lib\site-packages\pysolr.py", line 891, in add
    overwrite=overwrite, handler=handler)
  File "d:\python\lib\site-packages\pysolr.py", line 478, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "d:\python\lib\site-packages\pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
pysolr.SolrError: Solr responded with an error (HTTP 500): [Reason: Error 500 Server Error]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\python\lib\site-packages\mongo_connector\oplog_manager.py", line 267, in run
    docman.upsert(doc, ns, timestamp)
  File "d:\python\lib\site-packages\mongo_connector\util.py", line 46, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "d:\python\lib\site-packages\mongo_connector\compat.py", line 9, in reraise
    raise exctype(str(value)).with_traceback(trace)
  File "d:\python\lib\site-packages\mongo_connector\util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "d:\python\lib\site-packages\mongo_connector\doc_managers\solr_doc_manager.py", line 271, in upsert
    commitWithin=u(self.auto_commit_interval))
  File "d:\python\lib\site-packages\pysolr.py", line 891, in add
    overwrite=overwrite, handler=handler)
  File "d:\python\lib\site-packages\pysolr.py", line 478, in _update
    return self._send_request('post', path, message, {'Content-type': 'text/xml; charset=utf-8'})
  File "d:\python\lib\site-packages\pysolr.py", line 393, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
mongo_connector.errors.OperationFailed: Solr responded with an error (HTTP 500): [Reason: Error 500 Server Error]

**Comment by nyf1993** [comment]
in mongodb ,The size of a single document is about 10M ,There are about 400 of them
