### ISSUE TITLE
OperationFailed: The $v update field is only recognized internally

### ISSUE THREAD

**Issue by jaraco** [yougov/mongo-connector#836]
Although the 2.6 release was intended to fix issues with MongoDB 3.6, once the tests are run against 3.6, at least one failure emerges:

```
Unable to process oplog document {'ts': Timestamp(1539602183, 1), 't': 1, 'h': -7461047704647023425, 'v': 2, 'op': 'u', 'ns': 'test.test', 'ui': UUID('f0d3237e-5e7b-40dd-844a-b85cdd4b26e1'), 'o2': {'_id': ObjectId('5bc47705ca159707a75824cd')}, 'wall': datetime.datetime(2018, 10, 15, 11, 16, 23, 629000), 'o': {'$v': 1, '$set': {'b': [{'c': 10}, {'d': 11}]}}}
Traceback (most recent call last):
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/doc_managers/mongo_doc_manager.py", line 181, in update
    allowable_errors=[no_obj_error])['value']
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/database.py", line 516, in command
    codec_options, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/database.py", line 428, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/pool.py", line 477, in command
    collation=collation)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: The $v update field is only recognized internally
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/oplog_manager.py", line 274, in run
    ns, timestamp)
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/util.py", line 46, in wrapped
    reraise(new_type, exc_value, exc_tb)
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/compat.py", line 9, in reraise
    raise exctype(str(value)).with_traceback(trace)
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/util.py", line 35, in wrapped
    return f(*args, **kwargs)
  File "/home/travis/build/yougov/mongo-connector/mongo_connector/doc_managers/mongo_doc_manager.py", line 181, in update
    allowable_errors=[no_obj_error])['value']
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/database.py", line 516, in command
    codec_options, **kwargs)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/database.py", line 428, in _command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/pool.py", line 477, in command
    collation=collation)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
mongo_connector.errors.OperationFailed: The $v update field is only recognized internally
FAIL
```

**Comment by jaraco** [comment]
This project needs someone to dive into the error message, characterize the failure, and devise a solution. I’m pretty sure the solution is going to be to remove the $v from appropriate documents, but the real question is where. I know I’ve had to solve this issue before in jaraco.mongodb, but I’m not finding it now. Contributions welcome.

**Comment by padewitte** [comment]
I faced the error with a source and destination databases freshly migrated to MongoDB 3.6. I patched mongodb connector with the PR below and now my logs are no more polluted and my data looks correct.

**Comment by padewitte** [comment]
In case it could help here is the root cause : [https://jira.mongodb.org/browse/SERVER-32240](https://jira.mongodb.org/browse/SERVER-32240)
