### ISSUE TITLE
No module named 'mongo_connector.compat' error after upgrade to major version 3.0.0

### ISSUE THREAD

**Issue by ptsteadman** [yougov/mongo-connector#843]
I have a docker service configuring mongoconnector between elasticsearch5 and mongo, with a Dockerfile like so:

```
FROM python:latest
RUN pip install 'mongo-connector[elastic5]'
RUN pip install 'elastic2-doc-manager[elastic5]'
RUN pip install 'dnspython'

COPY ./docker-entrypoint.sh .

CMD ["/bin/bash", "docker-entrypoint.sh"];
```

After the recent new release of mongoconnector 3.0.0 on [pypi](https://pypi.org/project/mongo-connector/#history), mongoconnector fails to start with the error `No module named 'mongo_connector.compat'`. I was able to fix my issue by changing `RUN pip install 'mongo-connector[elastic5]'` to `RUN pip install 'mongo-connector[elastic5]==2.5.1'`, but I would like to know how to fix this issue so that we will be able to move to the next major version release.

Full trace:
```
2018-10-30 19:02:24Traceback (most recent call last):
2018-10-30 19:02:24 File "/usr/local/bin/mongo-connector", line 11, in <module>
2018-10-30 19:02:24 sys.exit(main())
2018-10-30 19:02:24 File "/usr/local/lib/python3.7/site-packages/mongo_connector/util.py", line 107, in wrapped
2018-10-30 19:02:24 func(*args, **kwargs)
2018-10-30 19:02:24 File "/usr/local/lib/python3.7/site-packages/mongo_connector/connector.py", line 1395, in main
2018-10-30 19:02:24 conf.parse_args()
2018-10-30 19:02:24 File "/usr/local/lib/python3.7/site-packages/mongo_connector/config.py", line 125, in parse_args
2018-10-30 19:02:24 option, dict((k, values.get(k)) for k in option.cli_names)
2018-10-30 19:02:24 File "/usr/local/lib/python3.7/site-packages/mongo_connector/connector.py", line 1108, in apply_doc_managers
2018-10-30 19:02:24 DocManager = import_dm_by_name(dm["docManager"])
2018-10-30 19:02:24 File "/usr/local/lib/python3.7/site-packages/mongo_connector/connector.py", line 1075, in import_dm_by_name
2018-10-30 19:02:24 return import_dm_by_path(full_name)
2018-10-30 19:02:24 File "/usr/local/lib/python3.7/site-packages/mongo_connector/connector.py", line 1095, in import_dm_by_path
2018-10-30 19:02:24 "vailable doc managers. ImportError:\n%s" % (package, exc)
2018-10-30 19:02:24mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.elastic2_doc_manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers. ImportError:
2018-10-30 19:02:24No module named 'mongo_connector.compat'
```

**Comment by jaraco** [comment]
Oh. I hadn’t considered that the doc managers might be using mongoconnector as a library. Either that module needs to be restored or those doc managers need a release also. I’ll get that fixed. In the meantime, workaround is to use mongo_connector<3.

**Comment by jaraco** [comment]
`mongo_connector` 3.0.1 is releasing which _should_ fix the issue.

**Comment by ptsteadman** [comment]
Confirmed, that fixes it! Thanks so much.
