### ISSUE TITLE
unexpectedly stopped! Shutting down

### ISSUE THREAD

**Issue by Leehory** [yougov/mongo-connector#870]
2019-05-15 16:02:03,709 [ALWAYS] mongo_connector.connector:50 - Starting mongo-connector version: 3.1.1
2019-05-15 16:02:03,709 [ALWAYS] mongo_connector.connector:50 - Python version: 3.7.0 (default, May 14 2019, 18:28:28) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
2019-05-15 16:02:03,709 [ALWAYS] mongo_connector.connector:50 - Platform: Linux-3.10.0-957.12.1.el7.x86_64-x86_64-with-centos-7.6.1810-Core
2019-05-15 16:02:03,709 [ALWAYS] mongo_connector.connector:50 - pymongo version: 3.8.0
2019-05-15 16:02:03,714 [ALWAYS] mongo_connector.connector:50 - Source MongoDB version: 3.6.12
2019-05-15 16:02:03,714 [ALWAYS] mongo_connector.connector:50 - Target DocManager: mongo_connector.doc_managers.solr_doc_manager version: 0.1.0
2019-05-15 16:02:04,898 [CRITICAL] mongo_connector.oplog_manager:714 - Exception during collection dump
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/solr_doc_manager-0.1.0-py3.7.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 296, in <genexpr>
    for i in range(self.chunk_size))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mongo_connector-3.1.1-py3.7.egg/mongo_connector/oplog_manager.py", line 668, in do_dump
    upsert_all(dm)
  File "/usr/local/lib/python3.7/site-packages/mongo_connector-3.1.1-py3.7.egg/mongo_connector/oplog_manager.py", line 651, in upsert_all
    dm.bulk_upsert(docs_to_dump(from_coll), mapped_ns, long_ts)
  File "/usr/local/lib/python3.7/site-packages/mongo_connector-3.1.1-py3.7.egg/mongo_connector/util.py", line 33, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/solr_doc_manager-0.1.0-py3.7.egg/mongo_connector/doc_managers/solr_doc_manager.py", line 296, in bulk_upsert
    for i in range(self.chunk_size))
RuntimeError: generator raised StopIteration
2019-05-15 16:02:04,899 [ERROR] mongo_connector.oplog_manager:723 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True, replicaset='fridomSolr'), 'local'), 'oplog.rs')
2019-05-15 16:02:05,724 [ERROR] mongo_connector.connector:411 - MongoConnector: OplogThread <OplogThread(Thread-2, started 139675974907648)> unexpectedly stopped! Shutting down

**Comment by leleTino** [comment]
Hi, any solution? I'm looking for fixing the same problem.

**Comment by junjun-git** [comment]
嗨，有什么办法吗？我正在寻找解决相同的问题。

**Comment by mithunj43** [comment]
any fix? even I am facing same issue !!!

**Comment by turivishal** [comment]
Any update?
