### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by sushifan** [yougov/mongo-connector#881]
Can reproduce every time.

1.  Run Mongo as a standalone instance.
2.  Restore several dozen dbs from snapshot (total size ~50gb).
3.  Convert the standalone to a replica set (simply follow the official docs).
4.  Use mongo_doc_manager to replicate to another mongo instance (which is empty).  At this point, the oplog is empty, so starting mongo-connector should dump all the dbs to the other instance.  However, I get this exception:

```
2019-08-23 22:31:34,303 [INFO] mongo_connector.oplog_manager:137 - OplogThread: Initializing oplog thread
2019-08-23 22:31:34,305 [INFO] __main__:402 - MongoConnector: Starting connection thread MongoClient(host=['mongo_master:27017'], document_class=dict, tz_aware=False, connect=True, replicaset='rs0')
2019-08-23 22:33:33,713 [ERROR] mongo_connector.util:98 - Call to <bound method OplogThread.init_cursor of <OplogThread(Thread-2, started 140500046702336)>> failed too many times in retry_until_ok
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mongo_connector/util.py", line 79, in retry_until_ok
    return func(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 810, in init_cursor
    self.update_checkpoint(self.rollback())
  File "/usr/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 901, in rollback
    last_docs.append(dm.get_last_doc())
  File "/usr/lib/python3.4/site-packages/mongo_connector/util.py", line 33, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/mongo_connector/doc_managers/mongo_doc_manager.py", line 307, in get_last_doc
    return max(docs_by_ts(), key=lambda x: x["_ts"])
ValueError: max() arg is an empty sequence
2019-08-23 22:33:33,715 [ERROR] mongo_connector.util:109 - Fatal Exception
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mongo_connector/util.py", line 107, in wrapped
    func(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 217, in run
    cursor, cursor_empty = retry_until_ok(self.init_cursor)
  File "/usr/lib/python3.4/site-packages/mongo_connector/util.py", line 79, in retry_until_ok
    return func(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 810, in init_cursor
    self.update_checkpoint(self.rollback())
  File "/usr/lib/python3.4/site-packages/mongo_connector/oplog_manager.py", line 901, in rollback
    last_docs.append(dm.get_last_doc())
  File "/usr/lib/python3.4/site-packages/mongo_connector/util.py", line 33, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/mongo_connector/doc_managers/mongo_doc_manager.py", line 307, in get_last_doc
    return max(docs_by_ts(), key=lambda x: x["_ts"])
ValueError: max() arg is an empty sequence
2019-08-23 22:33:34,494 [ERROR] __main__:411 - MongoConnector: OplogThread <OplogThread(Thread-2, stopped 140500046702336)> unexpectedly stopped! Shutting down
2019-08-23 22:33:34,494 [INFO] __main__:478 - MongoConnector: Stopping all OplogThreads
2019-08-23 22:33:34,495 [INFO] mongo_connector.doc_managers.mongo_doc_manager:130 - Mongo DocManager Stopped: If you will not target this system again with mongo-connector then you may drop the database __mongo_connector, which holds metadata for Mongo Connector.
```

Here's my config file:

```
{
    "mainAddress": "mongo_source:27017",
    "oplogFile": "/var/log/mongo-connector/oplog.timestamp",
    "noDump": false,
    "batchSize": -1,
    "verbosity": 2,
    "continueOnError": true,

    "logging": {"type": "file",
                "filename": "/var/log/mongo-connector/mongo-connector.log"},

    "docManagers": [{"docManager": "mongo_doc_manager", "targetURL": "mongo_destination:27017"}]
}
```

`mongo_source` is the hostname of the server mongo-connector is running on and `mongo_destination` points to another server via `/etc/hosts`.  Everything works if I restore from the same snapshot on the destination server and set noDump to true, i.e. replicate just the oplog.  So, the issue is definitely when trying to dump an existing source to an empty destination.

**Comment by razvvan** [comment]
@sushifan did you ever figure this out?

**Comment by sushifan** [comment]
> @sushifan did you ever figure this out?

Unfortunately, no.  Can't remember what workaround I ended up doing to overcome this, sorry.  But the issue was legitimate--it was reproducible every time.
