### ISSUE TITLE
bson.errors.InvalidBSON still an issue even when pymongo has C extensions.

### ISSUE THREAD

**Issue by burnsjake** [yougov/mongo-connector#882]
In trying to run mongo-connector between two replicasets running mongo 3.6.14, it fails with the dreaded InvalidBSON error. There is nothing in the target replicaset. I have installed the mongo connector fresh and verified that pymongo has the C extensions.  I have also tried installing and pinning an old pymongo (2.9) and mongo-connector (2.3.0) to no avail.

This is a log from a run of mongo-connector (3.1.1) with pymongo (3.9.0):
2019-08-28 16:19:51,512 [ALWAYS] mongo_connector.connector:50 - Starting mongo-connector version: 3.1.1
2019-08-28 16:19:51,512 [ALWAYS] mongo_connector.connector:50 - Python version: 3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.3.0]
2019-08-28 16:19:51,514 [ALWAYS] mongo_connector.connector:50 - Platform: Linux-5.0.0-25-lowlatency-x86_64-with-Ubuntu-19.04-disco
2019-08-28 16:19:51,514 [ALWAYS] mongo_connector.connector:50 - pymongo version: 3.9.0
2019-08-28 16:19:51,515 [WARNING] mongo_connector.connector:170 - MongoConnector: Can't find /home/ubuntu/venv/oplog.timestamp, attempting to create an empty progress log
2019-08-28 16:19:51,549 [ALWAYS] mongo_connector.connector:50 - Source MongoDB version: 3.6.14
2019-08-28 16:19:51,549 [ALWAYS] mongo_connector.connector:50 - Target DocManager: mongo_connector.doc_managers.mongo_doc_manager version: 3.1.1
2019-08-28 16:20:56,048 [CRITICAL] mongo_connector.oplog_manager:714 - Exception during collection dump
Traceback (most recent call last):
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/mongo_connector/oplog_manager.py", line 668, in do_dump
    upsert_all(dm)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/mongo_connector/oplog_manager.py", line 651, in upsert_all
    dm.bulk_upsert(docs_to_dump(from_coll), mapped_ns, long_ts)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/mongo_connector/util.py", line 33, in wrapped
    return f(*args, **kwargs)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/mongo_connector/doc_managers/mongo_doc_manager.py", line 237, in bulk_upsert
    for bulk_op, meta_bulk_op in iterate_chunks():
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/mongo_connector/doc_managers/mongo_doc_manager.py", line 218, in iterate_chunks
    doc = next(docs)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/mongo_connector/oplog_manager.py", line 592, in docs_to_dump
    for doc in cursor:
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/pymongo/cursor.py", line 1093, in _refresh
    self.__send_message(g)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/pymongo/cursor.py", line 955, in __send_message
    address=self.__address)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1347, in _run_operation_with_response
    exhaust=exhaust)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1465, in _retryable_read
    return func(session, server, sock_info, slave_ok)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1341, in _cmd
    unpack_res)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/pymongo/server.py", line 131, in run_operation_with_response
    user_fields=user_fields)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/pymongo/cursor.py", line 1030, in _unpack_response
    legacy_response)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/pymongo/message.py", line 1582, in unpack_response
    self.payload_document, codec_options, user_fields)
  File "/home/ubuntu/venv/mcon/lib/python3.7/site-packages/bson/__init__.py", line 1098, in _decode_all_selective
    return decode_all(data, codec_options)
bson.errors.InvalidBSON: year 46312 is out of range
2019-08-28 16:20:56,052 [ERROR] mongo_connector.oplog_manager:723 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient(host=['mongo03.mydomain.com:27017', 'mongo02.mydomain.com:27017', 'mongo01.mydomain.com:27017'], document_class=dict, tz_aware=False, connect=True, replicaset='rs01'), 'local'), 'oplog.rs')
2019-08-28 16:20:56,972 [ERROR] mongo_connector.connector:411 - MongoConnector: OplogThread <OplogThread(Thread-2, started 139676069381888)> unexpectedly stopped! Shutting down

**Comment by howardkhl** [comment]
Same issue

**Comment by howardkhl** [comment]
Someone made an attempt to ignore **bson.errors.InvalidBSON**
https://github.com/yougov/mongo-connector/pull/915/files
However I tried and did not work
