### ISSUE TITLE
Mongo Cluster Connect Issue

### ISSUE THREAD

**Issue by ASeaOtter** [yougov/mongo-connector#887]
Hi there,

I'm trying to use mongo-connector with the neo4j-doc-manager. I have a hosted MongoDB Atlas Cluster and am attempting to connect like

`mongo-connector -m mongodb+srv://<username>:<password>@dev01-kxgnt.mongodb.net/stage?retryWrites=true&w=majority&authSource=admin -t http://localhost:7474/db/data -d neo4j_doc_manager`

But I am receiving this error 

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/site-packages/mongo_connector/util.py", line 107, in wrapped
    func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mongo_connector/connector.py", line 356, in run
    self.main_conn.admin.command("buildInfo")["version"],
  File "/usr/local/lib/python3.7/site-packages/pymongo/database.py", line 730, in command
    read_preference, session) as (sock_info, slave_ok):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1301, in _socket_for_reads
    with self._get_socket(server, session) as sock_info:
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/pymongo/mongo_client.py", line 1223, in _get_socket
    self.__all_credentials, checkout=exhaust) as sock_info:
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/pymongo/pool.py", line 1128, in get_socket
    sock_info.check_auth(all_credentials)
  File "/usr/local/lib/python3.7/site-packages/pymongo/pool.py", line 712, in check_auth
    auth.authenticate(credentials, self)
  File "/usr/local/lib/python3.7/site-packages/pymongo/auth.py", line 564, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/local/lib/python3.7/site-packages/pymongo/auth.py", line 539, in _authenticate_default
    return _authenticate_scram(credentials, sock_info, 'SCRAM-SHA-1')
  File "/usr/local/lib/python3.7/site-packages/pymongo/auth.py", line 301, in _authenticate_scram
    res = sock_info.command(source, cmd)
  File "/usr/local/lib/python3.7/site-packages/pymongo/pool.py", line 613, in command
    user_fields=user_fields)
  File "/usr/local/lib/python3.7/site-packages/pymongo/network.py", line 167, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.7/site-packages/pymongo/helpers.py", line 159, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: Authentication failed.`

Any ideas for how I can get the authentication to work?

Thank you

**Comment by ASeaOtter** [comment]
Also I have verified that I'm using the correct username, password, and database.
