### ISSUE TITLE
guys.. any hints ?   neo4j docs say python 2.7 is ok.. but this repo says not. .. details.

### ISSUE THREAD

**Issue by johnda98** [yougov/mongo-connector#906]
mongo-connector -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager
/home/leveridge/.local/lib/python2.7/site-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
/home/leveridge/.local/lib/python2.7/site-packages/mongo_connector/compat.py:30: UserWarning: Python 2 support is deprecated and pending removal. Please run mongo-connector on Python 3. See https://github.com/yougov/mongo-connector/issues/829 for more details or to post concerns.
  "Python 2 support is deprecated and pending removal. Please "
Traceback (most recent call last):
  File "/home/leveridge/.local/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/home/leveridge/.local/lib/python2.7/site-packages/mongo_connector/util.py", line 109, in wrapped
    func(*args, **kwargs)
  File "/home/leveridge/.local/lib/python2.7/site-packages/mongo_connector/connector.py", line 1395, in main
    conf.parse_args()
  File "/home/leveridge/.local/lib/python2.7/site-packages/mongo_connector/config.py", line 125, in parse_args
    option, dict((k, values.get(k)) for k in option.cli_names)
  File "/home/leveridge/.local/lib/python2.7/site-packages/mongo_connector/connector.py", line 1108, in apply_doc_managers
    DocManager = import_dm_by_name(dm["docManager"])
  File "/home/leveridge/.local/lib/python2.7/site-packages/mongo_connector/connector.py", line 1075, in import_dm_by_name
    return import_dm_by_path(full_name)
  File "/home/leveridge/.local/lib/python2.7/site-packages/mongo_connector/connector.py", line 1095, in import_dm_by_path
    "vailable doc managers. ImportError:\n%s" % (package, exc)
mongo_connector.errors.InvalidConfiguration: Could not import mongo_connector.doc_managers.neo4j_doc_manager. It could be that this doc manager has been moved out of this project and is maintained elsewhere. Make sure that you have the doc manager installed alongside mongo-connector. Check the README for a list of available doc managers. ImportError:
cannot import name authenticate
leveridge@leveridge-PowerEdge-R710:~$ mongo -version

**Comment by johnda98** [comment]
I will subit a PR to tell neo4j docs to update to py3
