### ISSUE TITLE
Ok guys pip3 install worked a charm ! .. BUT last final step ! hiccup on permissions 

### ISSUE THREAD

**Issue by johnda98** [yougov/mongo-connector#908]
Sir.. i get the same permissions on logfile as one of your other users...    BUT in this case I can not run w/ sudo .. any ideas ?  it returns no found on the command w sudo prefix.. oddly

 "leveridge@leveridge-PowerEdge-R710:~$ sudo mongo-connector -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager
sudo: mongo-connector: command not found
"

here is the last happy lines of the mongo-connector fire up
leveridge@leveridge-PowerEdge-R710:~$ mongo-connector -m localhost:27017 -t http://localhost:7474/db/data -d neo4j_doc_manager
Traceback (most recent call last):
  File "/home/leveridge/.local/bin/mongo-connector", line 11, in <module>
    sys.exit(main())
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/util.py", line 107, in wrapped
    func(*args, **kwargs)
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/connector.py", line 1410, in main
    setup_logging(conf)
  File "/home/leveridge/.local/lib/python3.6/site-packages/mongo_connector/connector.py", line 1346, in setup_logging
    backupCount=conf["logging.rotationBackups"],
  File "/usr/lib/python3.6/logging/handlers.py", line 202, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
  File "/usr/lib/python3.6/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/home/leveridge/mongo-connector.log'

**Comment by johnda98** [comment]
may have it solved
