### ISSUE TITLE
failed too many times 

### ISSUE THREAD

**Issue by hbudia** [yougov/mongo-connector#935]
I want to copy data from on cluster to another mongo, but when try to run the connection seem failed. I can assure connect to both cluster. Here is the error I've got.

`connect=True, replicaset='rs0', tls=True), 'databasename'), 'collection_names') failed too many times in retry_until_ok
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mongo_connector/util.py", line 79, in retry_until_ok
    return func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/pymongo/collection.py", line 3164, in __call__
    "exists." % self.__name
TypeError: 'Collection' object is not callable. If you meant to call the 'collection_names' method on a 'Database' object it is failing because no such method exists.
`

I'm using mongo-connector version 3.1.1 and pymongo version 4.1.1.
Can anyone point me in the right direction?

**Comment by hbudia** [comment]
I'm resolving this by downgrading pymongo version to 2.9
